#!/bin/bash

sudo apt-get install -qq -y --force-yes nodejs npm

case "$TRAVIS_PYTHON_VERSION" in
    2*) MINICONDA="Miniconda"  ;;
    3*) MINICONDA="Miniconda3" ;;
     *) exit 1
esac

MINICONDA="$MINICONDA-$MINICONDA_VERSION-Linux-x86_64"
PHANTOMJS="phantomjs-$PHANTOMJS_VERSION-linux-x86_64"

MINICONDA_URL="http://repo.continuum.io/miniconda/$MINICONDA.sh"
PHANTOMJS_URL="https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOMJS.tar.bz2"

wget $MINICONDA_URL
bash $MINICONDA.sh -b -p $HOME/miniconda
rm -rf $MINICONDA.sh

mkdir $HOME/phantomjs
wget -O - $PHANTOMJS_URL | tar xj --strip-components 1 -C $HOME/phantomjs
