#!/bin/bash

python -c 'from bokeh import test; test()'
TESTS_RESULT="$?"

export BOKEH_SERVER_URL="http://localhost:$BOKEH_PORT/"
examples/test --bokeh-port=$BOKEH_PORT --ipython-port=$IPYTHON_PORT --phantomjs=$HOME/phantomjs/bin/phantomjs
EXAMPLES_RESULT="$?"

cd sphinx
make html
DOCS_RESULT="$?"
cd ..

if [[ $TESTS_RESULT -eq 1 -o $EXAMPLES_RESULT -eq 1 -o $DOCS_RESULT -eq 1 ]]
then
    exit 1
fi
